### ISSUE TITLE
404 Not Found Exercises for Classes

### ISSUE THREAD

**Issue by tanducmai** [bregman-arie/python-exercises#2]
When I click on [Objective & Instructions](https://github.com/bregman-arie/python-exercises/blob/main/exercises/classes/attributes.md) in the [Classes topic](https://github.com/bregman-arie/python-exercises/#classes), it displays the HTTP 404 so I think the link is broken now.

However, its [solution](https://github.com/bregman-arie/python-exercises/blob/main/solutions/classes/attributes.md) is available.

Please update the link for Objective & Instructions.

**Comment by bregman-arie** [comment]
Fixed. Thanks for reporting it :)
